# This file may be used to create an environment using: 
# $ conda env create --name <env> --file <this file>

name: ginr
channels:
    - defaults
    - pytorch 
    - nvidia
    - conda-forge

dependencies: 
    - python=3.9
    - numpy==1.23.4
    - pip 

    - pip:
        # install ginr and its dependencies
        - -r requirements.txt 
    
